import express from'express';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import crypto from'node:crypto';
const app=express(),port=Number(process.env.PORT)||3333,secret=process.env.JWT_SECRET||'segredo-apenas-para-desenvolvimento-local';app.use(express.json({limit:'10kb'}));
const users=[{id:crypto.randomUUID(),name:'Ricardo Cardoso',email:'demo@sentinela.dev',password:await bcrypt.hash('Sentinela123!',12),role:'Administrador',createdAt:new Date().toISOString()}];
const publicUser=({password,...user})=>user;const tokenFor=user=>jwt.sign({sub:user.id,email:user.email,role:user.role},secret,{expiresIn:'1h',issuer:'sentinela-api',audience:'sentinela-web'});
function auth(req,res,next){const value=req.headers.authorization;if(!value?.startsWith('Bearer '))return res.status(401).json({message:'Token de acesso ausente.'});try{req.auth=jwt.verify(value.slice(7),secret,{issuer:'sentinela-api',audience:'sentinela-web'});next()}catch{return res.status(401).json({message:'Sessão inválida ou expirada.'})}}
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.post('/api/auth/register',async(req,res)=>{const{name,email,password}=req.body??{};if(!name?.trim()||!email?.includes('@')||typeof password!=='string'||password.length<8)return res.status(400).json({message:'Informe nome, e-mail válido e senha com pelo menos 8 caracteres.'});if(users.some(user=>user.email===email.toLowerCase()))return res.status(409).json({message:'Este e-mail já está cadastrado.'});const user={id:crypto.randomUUID(),name:name.trim(),email:email.toLowerCase(),password:await bcrypt.hash(password,12),role:'Membro',createdAt:new Date().toISOString()};users.push(user);res.status(201).json({token:tokenFor(user),user:publicUser(user)})});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body??{},user=users.find(item=>item.email===String(email).toLowerCase());if(!user||!await bcrypt.compare(String(password),user.password))return res.status(401).json({message:'E-mail ou senha incorretos.'});res.json({token:tokenFor(user),user:publicUser(user)})});
app.get('/api/auth/me',auth,(req,res)=>{const user=users.find(item=>item.id===req.auth.sub);if(!user)return res.status(404).json({message:'Usuário não encontrado.'});res.json({user:publicUser(user)})});
app.listen(port,()=>console.log(`Sentinela API em http://localhost:${port}`));
