import{FormEvent,useEffect,useState}from'react';import{Activity,ArrowRight,CheckCircle2,Eye,EyeOff,Fingerprint,KeyRound,Lock,LogOut,ShieldCheck,UserRound}from'lucide-react';
type User={id:string;name:string;email:string;role:string;createdAt:string};const KEY='sentinela.token';
async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}}),data=await response.json();if(!response.ok)throw new Error(data.message);return data}
function App(){const[user,setUser]=useState<User|null>(null),[mode,setMode]=useState<'login'|'register'>('login'),[loading,setLoading]=useState(Boolean(localStorage.getItem(KEY))),[error,setError]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState({name:'',email:'',password:''});
useEffect(()=>{const token=localStorage.getItem(KEY);if(!token){setLoading(false);return}request('/api/auth/me',{headers:{Authorization:`Bearer ${token}`}}).then(data=>setUser(data.user)).catch(()=>localStorage.removeItem(KEY)).finally(()=>setLoading(false))},[]);
async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const data=await request(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem(KEY,data.token);setUser(data.user)}catch(err){setError(err instanceof Error?err.message:'Falha na autenticação.')}finally{setLoading(false)}}
function logout(){localStorage.removeItem(KEY);setUser(null);setForm({name:'',email:'',password:''})}
if(loading&&!user)return <main className="loading"><Fingerprint/><span>Validando sua sessão...</span></main>;
if(user)return <main className="dashboard"><aside><div className="brand"><ShieldCheck/>sentinela</div><nav><a className="active"><Activity/>Visão geral</a><a><UserRound/>Minha conta</a><a><KeyRound/>Segurança</a></nav><button onClick={logout}><LogOut/>Encerrar sessão</button></aside><section><header><div><span>ÁREA PROTEGIDA</span><h1>Bem-vindo, {user.name.split(' ')[0]}.</h1></div><div className="avatar">{user.name.split(' ').map(part=>part[0]).slice(0,2).join('')}</div></header><div className="verified"><CheckCircle2/><div><strong>Sessão autenticada com sucesso</strong><p>Esta página só pode ser acessada com um token JWT válido.</p></div></div><div className="cards"><article><span>PERFIL</span><h2>{user.name}</h2><p>{user.email}</p><i>{user.role}</i></article><article><span>SEGURANÇA</span><h2>Proteção ativa</h2><p>Token assinado • Expiração em 1 hora</p><i>JWT</i></article><article><span>CONTA CRIADA</span><h2>{new Date(user.createdAt).toLocaleDateString('pt-BR')}</h2><p>Identificador: {user.id.slice(0,8)}</p><i>Ativa</i></article></div><div className="token-flow"><h2>Como sua sessão funciona</h2>{[['01','Credenciais verificadas'],['02','Token assinado pela API'],['03','Rota protegida liberada']].map(([n,t])=><div key={n}><b>{n}</b><span>{t}</span><ArrowRight/></div>)}</div></section></main>;
return <main className="auth"><section className="auth-story"><div className="brand"><ShieldCheck/>sentinela</div><div><span>AUTENTICAÇÃO SEM ATALHOS</span><h1>Segurança que<br/>você <em>entende.</em></h1><p>Uma experiência de acesso simples por fora e cuidadosamente protegida por dentro.</p><ul><li><CheckCircle2/>Senhas protegidas com bcrypt</li><li><CheckCircle2/>Tokens assinados e com expiração</li><li><CheckCircle2/>Rotas privadas verificadas pela API</li></ul></div><small>JWT • BCRYPT • EXPRESS</small></section><section className="auth-form"><div className="form-wrap"><span>{mode==='login'?'BEM-VINDO DE VOLTA':'CRIE SUA CONTA'}</span><h2>{mode==='login'?'Acesse sua conta':'Comece com segurança'}</h2><p>{mode==='login'?'Use suas credenciais para continuar.':'Preencha seus dados para criar um acesso protegido.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Nome completo<div><UserRound/><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Como devemos chamar você?"/></div></label>}<label>E-mail<div><UserRound/><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="voce@empresa.com"/></div></label><label>Senha<div><Lock/><input type={show?'text':'password'} required minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo de 8 caracteres"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="form-error">{error}</div>}<button className="submit" disabled={loading}>{loading?'Autenticando...':mode==='login'?'Entrar com segurança':'Criar minha conta'}<ArrowRight/></button></form>{mode==='login'&&<div className="demo"><strong>Acesso demonstrativo</strong><span>demo@sentinela.dev</span><span>Sentinela123!</span><button onClick={()=>setForm({...form,email:'demo@sentinela.dev',password:'Sentinela123!'})}>Usar acesso</button></div>}<p className="switch">{mode==='login'?'Ainda não tem conta?':'Já possui uma conta?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Cadastre-se':'Entrar'}</button></p></div></section></main>}
export default App
